# .github/workflows/main.yml

name: Python application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # This step now installs dependencies AND fixes the security policy
      - name: Install system dependencies and fix ImageMagick policy
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          # This is the new line that fixes the error
          sudo sed -i 's/<policy domain="path" rights="none" pattern="@\*"\/>/<policy domain="path" rights="read|write" pattern="@\*"\/>/g' /etc/ImageMagick-6/policy.xml

      - name: Run main script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PEXELS_KEY: ${{ secrets.PEXELS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python app.py "INTERESTING HISTORY FACTS"
        
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: rendered_video.mp4
          retention-days: 7
