# File: .github/workflows/main.yml

name: Run Python Application

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up a Python environment for use in the workflow
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Installs dependencies from requirements.txt
      #    Note: Corrected your file name from "requirements.text" to "requirements.txt"
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Runs the main Python script
      - name: Run Python script
        env:
          # IMPORTANT: These should be configured as encrypted secrets in your
          # repository's settings (Settings > Secrets and variables > Actions)
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          PEXELS_KEY: ${{ secrets.PEXELS_API_KEY }}
          GROQ_KEY: ${{secrets.GROQ_API_KEY }}
        run: python app.py "Topic name"
